---
- name: Longhorn
  delegate_to: "{{ longhorn_delegate_to }}"
  run_once: true
  environment:
    KUBECONFIG: "{{ longhorn_kubeconfig_path }}"
  block:
    - name: Add helm repo
      kubernetes.core.helm_repository:
        repo_name: "{{ longhorn_repo_name }}"
        repo_url: "{{ longhorn_chart_url }}"

    - name: Template namespace
      ansible.builtin.template:
        src: templates/longhorn-namespace.j2
        dest: /tmp/longhorn-namespace.yml
        force: true

    - name: Create namespace
      ansible.builtin.command: "{{ longhorn_kubectl_path }} apply -f /tmp/longhorn-namespace.yml"
      changed_when: false

    - name: Template priority class
      ansible.builtin.template:
        src: templates/longhorn-priority-class.j2
        dest: /tmp/longhorn-priority-class.yml
        force: true
      when: longhorn_create_priority_class | bool

    - name: Create priority class
      ansible.builtin.command: "{{ longhorn_kubectl_path }} apply -f /tmp/longhorn-priority-class.yml"
      changed_when: false
      when: longhorn_create_priority_class | bool

    - name: Create longhorn config
      ansible.builtin.template:
        src: "longhorn-config.j2"
        dest: "{{ longhorn_config_path }}"
        mode: "0600"

    # - name: Install Longhorn
    #   kubernetes.core.helm:
    #     name: "{{ longhorn_release_name }}"
    #     chart_ref: "{{ longhorn_chart_name }}"
    #     chart_version: "{{ longhorn_version }}"
    #     release_namespace: "{{ longhorn_namespace }}"
    #     create_namespace: false
    #     update_repo_cache: true
    #     values_files:
    #       - "{{ longhorn_config_path }}"
    #     wait: true
    #     timeout: 10m0s
