---
# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html#notes
- name: Install helm diff
  kubernetes.core.helm_plugin:
    plugin_path: "https://github.com/databus23/helm-diff"
    plugin_version: 3.9.5
    state: present
  environment:
    KUBECONFIG: "{{ longhorn_kubeconfig_path }}"
