---
- name: Label user component nodes
  ansible.builtin.command: "{{ longhorn_kubectl_path }} label nodes --overwrite {{ groups[longhorn_user_component_nodes] | join(' ') }} {{ item.key }}={{ item.value }}"
  environment:
    KUBECONFIG: "{{ longhorn_kubeconfig_path }}"
  loop: "{{ longhorn_user_component_labels }}"
  changed_when: true
